// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("MyProvider.DesignTime")>]
[<assembly: AssemblyProductAttribute("MyProvider")>]
[<assembly: AssemblyDescriptionAttribute("This library is for the .NET platform implementing MyProvider.")>]
[<assembly: AssemblyVersionAttribute("1.0.0")>]
[<assembly: AssemblyFileVersionAttribute("1.0.0")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "MyProvider.DesignTime"
    let [<Literal>] AssemblyProduct = "MyProvider"
    let [<Literal>] AssemblyDescription = "This library is for the .NET platform implementing MyProvider."
    let [<Literal>] AssemblyVersion = "1.0.0"
    let [<Literal>] AssemblyFileVersion = "1.0.0"
