name: Build and Test

on:
  pull_request:
    branches:
    - master

jobs:
  build:

    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest]
        dotnet: [5.0.400]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v1

    - name: Setup .NET Core
      # Fix for https://github.com/actions/setup-dotnet/issues/29#issuecomment-548740241
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dotnet }}

    - name: Build on Windows
      if: matrix.os == 'windows-latest'
      run: .\build.cmd

    - name: Build on Unix
      if: matrix.os != 'windows-latest'
      run: ./build.sh
